- id: 'best-service'
  tier:
    name: '1'
    description: 'the most important services'
  owner: 'Best Team'
  channel: '#best-team'
  repository:
    name: 'best-service'
    location: 'https://myrepositories.com/best-service'
  selfLocation: 'https://best-service'
  metricsLocation: 'https://metrics-provider/best-service'
  docsLocation: 'https://best-service/docs'
  logsLocation: 'https://logs-provider/best-service'
- id: 'tier-2-service'
  tier:
    name: '2'
    description: 'The somewhat important services'
  owner: 'Second Best Team'
  channel: '#second-best-team'
  repository:
    name: 'tier-2-service'
    location: 'https://myrepositories.com/tier-2-service'
  selfLocation: 'https://tier-2-service'
  metricsLocation: 'https://metrics-provider/tier-2-service'
  docsLocation: 'https://tier-2-service/docs'
  logsLocation: 'https://logs-provider/tier-2-service'
- id: 'worst-service'
  tier:
    name: '3'
    description: 'Who cares right?'
  owner: 'Wrong Team'
  channel: '#wrong-team'
  repository:
    name: 'worst-service'
    location: 'https://myrepositories.com/worst-service'
  selfLocation: 'https://worst-service'
  metricsLocation: 'https://metrics-provider/worst-service'
  docsLocation: 'https://worst-service/docs'
  logsLocation: 'https://logs-provider/worst-service'
- id: 'second-service'
  tier:
    name: '3'
    description: 'Who cares right?'
  owner: 'Best Team'
  channel: '#best-team-second-service'
  repository:
    name: 'second-service'
    location: 'https://myrepositories.com/second-service'
  selfLocation: 'https://second-service'
  metricsLocation: 'https://metrics-provider/second-service'
  docsLocation: 'https://second-service/docs'
  logsLocation: 'https://logs-provider/second-service'
- id: 'empty-service'

