# Spring
server:
  port: 8090

# Hotpot
hotpot:
  web-api:
    base-url: "v1"
    enabled: true
  metrics:
    enabled: true
    provider-type: yaml
    metrics-definition: metrics.yaml
    objectives-definition: objectives.yaml
