# Spring
server:
  port: 8090

# Hotpot
hotpot:
  web-api:
    base-url: "v1"
    enabled: true
  metrics:
    enabled: true
  static-data:
    enabled: true
    type: yaml
    metrics-location: metrics.yaml
    objectives-location: objectives.yaml
    services-location: services.yaml
    metadata-precedence: 1
