name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.12
        uses: actions/setup-java@v1
        with:
          java-version: 1.12
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish to githbub package registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Get the version from the tag ('refs/tags/xxx')
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          ./gradlew -Pversion=${NEW_VERSION} publish --info

      - name: Publish to bintray
        env:
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        # Get the version from the tag ('refs/tags/xxx')
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          ./gradlew -Pversion=${NEW_VERSION} bintrayUpload --info